version: '3'

services:
  app:
    build:
      context: ./app
    image: leandrosoares/conam
    ports:
      - "80:80"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=conam
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKER_HOST=broker
      - KAFKA_BROKER_PORT=9092
    volumes:
      - ./app/src:/app
  
  portal:
    build:
      context: ./portal
    image: leandrosoares/conam-portal
    ports:
      - "8080:80"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=conam
      - KAFKA_BROKER_HOST=broker
      - KAFKA_BROKER_PORT=9092
    volumes:
      - ./portal/src:/app

  logger:
    build:
      context: ./logger
    image: leandrosoares/conam_logger
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=conam
      - KAFKA_BROKER_HOST=broker
      - KAFKA_BROKER_PORT=9092
    depends_on:
      - postgres
      - broker
    volumes:
      - ./logger/src:/logger

  redis:
    image: 'redis:alpine'

  postgres:
    image: 'postgres:12-alpine'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=conam
    ports:
      - '5432:5432'
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1