apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - name: conam-app
          image: leandroconam/conam-app:v12
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
            - name: DB_HOST
              value: database-conam.clp7coyawqkp.us-east-1.rds.amazonaws.com
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: conam
            - name: DB_PASSWORD
              value: 37iTbWHx35sY
            - name: DB_DATABASE
              value: postgres
            - name: KAFKA_BROKER_HOST
              value: kafka-service
            - name: KAFKA_BROKER_PORT
              value: "9092"