apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - name: conam-app
          image: leandrosoares/conam
          ports:
            - containerPort: 80
          imagePullPolicy: Always