apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: logger
  template:
    metadata:
      labels:
        component: logger
    spec:
      containers:
        - name: conam-logger
          image: leandrosoares/conam-logger
          imagePullPolicy: Always
          env: 
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
            - name: DB_HOST
              value: postgres-cluster-ip-service
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: root
            - name: DB_DATABASE
              value: conam
            - name: KAFKA_BROKER_HOST
              value: broker-cluster-ip-service
            - name: KAFKA_BROKER_PORT
              value: "9092"