apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: logger
  template:
    metadata:
      labels:
        component: logger
    spec:
      containers:
        - name: conam-logger
          image: leandroconam/conam-logger
          imagePullPolicy: Always
          env: 
            - name: DB_HOST
              value: database-conam.clp7coyawqkp.us-east-1.rds.amazonaws.com
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: conam
            - name: DB_PASSWORD
              value: 37iTbWHx35sY
            - name: DB_DATABASE
              value: postgres
            - name: KAFKA_BROKER_HOST
              value: kafka-service
            - name: KAFKA_BROKER_PORT
              value: "9092"